# PosgreSQL version 0.18.4
#   gem install pg
#
#   gem 'postgresql'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  user: devruby
  password: ruby

development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  user: devruby
  password: ruby
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000
  user: devruby
  password: ruby

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
  user: devruby
  password: ruby
